apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1-smoketest-namespace.yaml
  - 2-smoketest-pvc.yaml
  - 3-smoketest-deployment.yaml
  - 4-smoketest-service.yaml
  - 5-smoketest-ingress.yaml
